FROM docker.io/alpine

RUN apk add --update --no-cache weechat

RUN addgroup -S fritz && adduser -S fritz -G fritz
USER fritz

CMD ["/usr/bin/weechat", "--run-command", "/server add irc-server irc-server; /connect irc-server"]
