FROM docker.io/alpine

RUN apk add --update --no-cache ngircd

COPY ngircd.conf /etc/ngircd/ngircd.conf

EXPOSE 6667

RUN addgroup -S fritz && adduser -S fritz -G fritz
USER fritz

CMD ["/usr/sbin/ngircd", "--nodaemon"]
