apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: irc-server
  name: irc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: irc-server
  template:
    metadata:
      labels:
        app: irc-server
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
      containers:
        - name: irc-server
          image: quay.io/ssorj/connectathon-irc-server
          ports:
            - containerPort: 6667
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
