apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sql-database
  name: sql-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-database
  template:
    metadata:
      labels:
        app: sql-database
    spec:
      containers:
        - name: sql-database
          image: quay.io/ssorj/connectathon-sql-database
          ports:
            - containerPort: 5432
---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: sql-database
#   name: sql-database
# spec:
#   ports:
#   - port: 5432
#     protocol: TCP
#     targetPort: 5432
#   selector:
#     app: sql-database
#   type: LoadBalancer
