apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sql-database
  name: sql-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-database
  template:
    metadata:
      labels:
        app: sql-database
    spec:
      containers:
        - name: sql-database
          image: quay.io/ssorj/botnet-sql-database
          ports:
            - containerPort: 5432
