apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hostbot
  name: hostbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostbot
  template:
    metadata:
      labels:
        app: hostbot
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
      containers:
        - name: hostbot
          image: quay.io/ssorj/botnet-hostbot
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
